### PR TITLE
Release v6

### PR DESCRIPTION
**Pull request by JuiP**
@quozl @chimosky please review and merge :)

### CODE REVIEW

**Comment by quozl** [comment]
Thanks.  Reviewed.  Additions to NEWS are in an unusual format.

**Comment by JuiP** [comment]
Yes, I noticed the additions before this version were in a different format, so I haven't changed the format for NEWS. However, I can instead change the format of NEWS additions for previous versions. Which one is best?

**Comment by quozl** [comment]
Thanks.  I guess keep the style as it is.  It was 12 years ago that it was last changed.

**Comment by chimosky** [comment]
Reviewed, thanks.

**Pull request merged**
