### PR TITLE
flake8 fixes

### PR DESCRIPTION
**Pull request by chimosky**

### CODE REVIEW

**Comment by quozl** [comment]
Please resolve conflicts.

**Comment by chimosky** [comment]
@quozl, kindly review.

**Comment by quozl** [comment]
Thanks.  Reviewed to a713769.  Please proceed; there are 107 more flake8 fixes to make, and a reference to undefined module `telepathy` in `_joined_cb` of `collaboration.py` which shows no testing of https://github.com/sugarlabs/playgo-activity/pull/11.  These should be fixed before a release.

**Comment by chimosky** [comment]
Thanks, but I don't see the reference to `telepathy` in `_joined_cb` of `collaboration.py`.

**Comment by chimosky** [comment]
@quozl, kindly review.

**Comment by quozl** [comment]
> I don't see the reference to `telepathy` in `_joined_cb` of `collaboration.py`. 

It was in a713769.  I've fetched again from your branch, checked out that commit, and run flake8, and it shows several instances like this;

```
collaboration.py:75:25: F821 undefined name 'telepathy'
collaboration.py:213:21: F821 undefined name 'telepathy'
collaboration.py:215:25: F821 undefined name 'telepathy'
collaboration.py:216:33: F821 undefined name 'telepathy'
collaboration.py:219:37: F821 undefined name 'telepathy'
collaboration.py:220:52: F821 undefined name 'telepathy'
```

Looking at the file at that point;  [`collaboration.py`](https://github.com/sugarlabs/playgo-activity/blob/a7137695ae1fa2d2db47dfa0289e6ca083da46dd/collaboration.py) shows the import of the static binding is removed, the import of the PyGObject binding is added, but scrolling down there are still references to the static binding module name `telepathy`.  It is as if you did not correctly merge changes from the _master_ branch.  Looking at the file there (4223259), flake8 reports no problems with the name `telepathy`.

Since then you've removed a713769 from your _flake8-fixes_ branch, leaving just cf98956, and then added b1442f4, resulting in conflicts again!

Please resolve conflicts.

Please add to your "before I commit" checklist the following;
* are all the changes shown by "git diff" desired for the commit?
* does the activity start?

Thanks!

**Comment by chimosky** [comment]
> Please add to your "before I commit" checklist the following;
>  - are all the changes shown by "git diff" desired for the commit?
>  - does the activity start?

I'll make them __bolder__ than they are, including rebasing before new changes.  
    


Conflicts resolved, the PR was sent the same time as #11, i think the fact that they weren't merged the same time caused the conflict - i forgot to rebase -. Thanks.
@quozl, kindly review.

**Comment by quozl** [comment]
Reviewed to 260e860.  Good progress.  Please continue; using python2 flake8 on Ubuntu 16.04 there are 21 further issues, and if E402 is turned off using a .flake8 file, there are 41 issues.

**Comment by chimosky** [comment]
@quozl, kindly review.

**Comment by quozl** [comment]
Thanks.

* changed coding from `UTF-8` to `utf-8`,
* reduced number of lines in some calls, as vertical space should be kept to a minimum to aid comprehension,
* used a conditional expression in call to Gdk.cairo_set_source_pixbuf,
* combined a multi-line string constant into one line,
* due to conflicts, merged by hand and pushed as https://github.com/sugarlabs/playgo-activity/commit/e3ead571b538026fd06dcf1c03bc0994a8b30677

**Pull request closed without merging**
